ALTER TABLE "Car"
  ADD COLUMN IF NOT EXISTS "variant" TEXT,
  ADD COLUMN IF NOT EXISTS "condition" TEXT,
  ADD COLUMN IF NOT EXISTS "bodyType" TEXT,
  ADD COLUMN IF NOT EXISTS "sellerType" TEXT,
  ADD COLUMN IF NOT EXISTS "driveType" TEXT,
  ADD COLUMN IF NOT EXISTS "firstRegistration" TEXT,
  ADD COLUMN IF NOT EXISTS "ownersCount" INTEGER,
  ADD COLUMN IF NOT EXISTS "weightKg" INTEGER,
  ADD COLUMN IF NOT EXISTS "powerKw" INTEGER,
  ADD COLUMN IF NOT EXISTS "powerHp" INTEGER,
  ADD COLUMN IF NOT EXISTS "displacementCc" INTEGER,
  ADD COLUMN IF NOT EXISTS "fuelConsumption" TEXT,
  ADD COLUMN IF NOT EXISTS "co2Emission" INTEGER,
  ADD COLUMN IF NOT EXISTS "co2Class" TEXT,
  ADD COLUMN IF NOT EXISTS "emissionSticker" TEXT,
  ADD COLUMN IF NOT EXISTS "seats" INTEGER,
  ADD COLUMN IF NOT EXISTS "doors" TEXT,
  ADD COLUMN IF NOT EXISTS "huUntil" TEXT,
  ADD COLUMN IF NOT EXISTS "airConditioning" TEXT,
  ADD COLUMN IF NOT EXISTS "parkingAssist" TEXT,
  ADD COLUMN IF NOT EXISTS "airbags" TEXT,
  ADD COLUMN IF NOT EXISTS "color" TEXT,
  ADD COLUMN IF NOT EXISTS "interior" TEXT,
  ADD COLUMN IF NOT EXISTS "towingCapacityBrakedKg" INTEGER,
  ADD COLUMN IF NOT EXISTS "towingCapacityUnbrakedKg" INTEGER,
  ADD COLUMN IF NOT EXISTS "cylinders" INTEGER,
  ADD COLUMN IF NOT EXISTS "tankVolumeL" INTEGER,
  ADD COLUMN IF NOT EXISTS "category" TEXT,
  ADD COLUMN IF NOT EXISTS "trimLine" TEXT,
  ADD COLUMN IF NOT EXISTS "origin" TEXT;

CREATE TABLE IF NOT EXISTS "SavedCar" (
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "carId" INTEGER NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SavedCar_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "SavedCar_carId_fkey" FOREIGN KEY ("carId") REFERENCES "Car"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "SavedCar_userId_carId_key" ON "SavedCar"("userId", "carId");
